"""
gemini_client.py
----------------
Vertex AI / Gemini 1.5 Pro integration for SOAP note generation.

Responsibilities:
- Build the clinical documentation prompt with system instructions and
  few-shot examples
- Send the cleaned transcript to Gemini 1.5 Pro via the Vertex AI SDK
- Parse and validate the structured JSON response
- Return a typed SOAPNote dataclass
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Any

import vertexai
from vertexai.generative_models import (
    GenerationConfig,
    GenerativeModel,
    HarmBlockThreshold,
    HarmCategory,
    Part,
    SafetySetting,
)

from utils import GeminiError, get_logger, retry_with_backoff

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

GCP_PROJECT: str = os.environ["GCP_PROJECT"]
GCP_REGION: str = os.environ.get("GCP_REGION", "YOUR_GCP_REGION")
GEMINI_MODEL: str = "gemini-1.5-pro-002"

# Generation parameters tuned for clinical documentation consistency.
_GENERATION_CONFIG = GenerationConfig(
    temperature=0.2,            # Low temperature for deterministic, factual output
    top_p=0.9,
    top_k=40,
    max_output_tokens=4096,
    response_mime_type="application/json",  # Enforce JSON output
)

# Disable safety filters that would incorrectly block medical content.
_SAFETY_SETTINGS: list[SafetySetting] = [
    SafetySetting(category=HarmCategory.HARM_CATEGORY_HARASSMENT,        threshold=HarmBlockThreshold.BLOCK_NONE),
    SafetySetting(category=HarmCategory.HARM_CATEGORY_HATE_SPEECH,       threshold=HarmBlockThreshold.BLOCK_NONE),
    SafetySetting(category=HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold=HarmBlockThreshold.BLOCK_NONE),
    SafetySetting(category=HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold=HarmBlockThreshold.BLOCK_NONE),
]

# Required keys in the Gemini response JSON.
_REQUIRED_SOAP_KEYS: frozenset[str] = frozenset(
    {
        "subjective",
        "objective",
        "assessment",
        "plan",
        "session_duration_minutes",
        "presenting_concerns",
        "risk_assessment",
    }
)

# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------


@dataclass
class SOAPNote:
    """
    Structured SOAP note generated by Gemini 1.5 Pro.

    Fields:
        subjective: Patient's self-reported symptoms, concerns, and history
            as described during the session.
        objective: Clinician's observable findings — affect, behavior,
            cognition, appearance.
        assessment: Clinical formulation, diagnostic impressions, progress
            toward treatment goals.
        plan: Next steps — homework, referrals, medication adjustments,
            next session focus.
        session_duration_minutes: Estimated session length extracted from
            transcript timing.
        presenting_concerns: Bullet list of the primary concerns raised
            in the session.
        risk_assessment: Brief statement on any safety concerns (suicidal
            ideation, self-harm, harm to others). "None reported" if absent.
        raw_json: The original JSON dict from Gemini (for auditing).
    """

    subjective: str
    objective: str
    assessment: str
    plan: str
    session_duration_minutes: int
    presenting_concerns: list[str]
    risk_assessment: str
    raw_json: dict[str, Any] = field(default_factory=dict, repr=False)


# ---------------------------------------------------------------------------
# System Instruction
# ---------------------------------------------------------------------------

_SYSTEM_INSTRUCTION = """
You are a licensed clinical documentation assistant helping behavioral health
therapists produce structured SOAP notes from session transcripts.

Your output must be a valid JSON object with exactly these keys:
  - "subjective": string — What the patient reported. Use first-person paraphrase
    (e.g., "Patient reports feeling..."). Do not include the therapist's words.
  - "objective": string — Clinician-observable data: patient's affect, demeanor,
    speech patterns, engagement level, and any notable behavioral observations.
    Infer these from how the patient communicates in the transcript.
  - "assessment": string — Clinical formulation. Summarize the patient's current
    functional status, progress toward stated treatment goals, and any diagnostic
    considerations raised by this session's content.
  - "plan": string — Interventions agreed upon, homework assigned, referrals
    discussed, topics for next session, and any safety planning steps.
  - "session_duration_minutes": integer — Estimated session length in minutes,
    derived from the transcript timestamps or content. Use 50 if unknown.
  - "presenting_concerns": array of strings — 3–7 bullet-point concerns raised
    by the patient during this session (e.g., "Work-related stress", "Sleep
    difficulties", "Relationship conflict").
  - "risk_assessment": string — Any mentions of suicidal ideation, self-harm
    urges, harm to others, or substance use crises. Write "No safety concerns
    reported this session." if none are present. Do not omit this field.

Constraints:
  - Do not invent clinical details not present in the transcript.
  - Do not include the patient's name, date of birth, or other PHI identifiers.
  - Write in professional clinical language appropriate for a medical record.
  - If the transcript is too short or unclear to complete a section, write
    "Insufficient data from this session." for that section.
  - Return ONLY valid JSON. No markdown, no explanation, no code fences.
""".strip()

# ---------------------------------------------------------------------------
# Few-Shot Examples (Synthetic — No Real PHI)
# ---------------------------------------------------------------------------

_FEW_SHOT_EXAMPLES: list[dict[str, str]] = [
    {
        "transcript": """
Therapist: How have you been feeling since our last session?

Patient: Honestly, pretty anxious. Work has been overwhelming — my manager
keeps adding to my plate and I'm sleeping maybe five hours a night. I had
a panic attack on Tuesday, first one in a few months.

Therapist: I'm sorry to hear that. Can you tell me more about what triggered it?

Patient: I was in a meeting and started thinking about the project deadline.
My heart started racing and I had to step out. It lasted about ten minutes.

Therapist: Let's talk about some grounding strategies you can use in those moments.
We discussed diaphragmatic breathing last time — were you able to practice it?

Patient: A little. It helps when I remember to do it. I also started the
journaling you suggested, which I think is helping.

Therapist: That's great progress. Let's add a brief body scan each morning
before work. We'll also revisit your thought records next session to look
at the catastrophic thinking patterns.
""",
        "soap_note": json.dumps(
            {
                "subjective": "Patient reports increased anxiety over the past week, attributing it to work demands and a heavy project load assigned by their manager. Reports reduced sleep (approximately 5 hours per night). Describes a panic attack on Tuesday lasting approximately 10 minutes, triggered by thoughts of a project deadline during a meeting. Reports partial adherence to diaphragmatic breathing exercises and has begun journaling as previously assigned.",
                "objective": "Patient presented as engaged and forthcoming. Affect appeared mildly anxious but appropriate to content. Speech was coherent and goal-directed. Patient demonstrated insight into triggers and described active coping attempts.",
                "assessment": "Patient continues to struggle with anxiety symptoms, particularly in occupational contexts, with a recurrence of panic symptoms after a period of relative remission. Positive response to behavioral interventions (journaling) noted. Partial adherence to breathing exercises suggests skill acquisition is in progress but not yet automatic. Treatment focus remains on cognitive restructuring and somatic symptom management.",
                "plan": "1. Introduce morning body scan practice (5 minutes before work). 2. Continue journaling daily. 3. Review thought records next session to identify catastrophizing patterns. 4. Patient to practice diaphragmatic breathing during at least one stressful moment per day and log outcome. 5. Follow up on workplace situation and sleep hygiene at next session.",
                "session_duration_minutes": 50,
                "presenting_concerns": [
                    "Workplace stress and increased workload",
                    "Sleep difficulties (5 hours/night)",
                    "Recurrence of panic attack symptoms",
                    "Partial adherence to coping skills",
                ],
                "risk_assessment": "No safety concerns reported this session.",
            }
        ),
    },
]


# ---------------------------------------------------------------------------
# Gemini Client
# ---------------------------------------------------------------------------


class GeminiClient:
    """
    Client for generating structured SOAP notes via Vertex AI Gemini 1.5 Pro.

    Initializes the Vertex AI SDK once on construction. The GenerativeModel
    instance is reused across calls within the same function instance (warm
    start), which avoids re-initializing the SDK on every invocation.
    """

    def __init__(self) -> None:
        vertexai.init(project=GCP_PROJECT, location=GCP_REGION)
        self._model = GenerativeModel(
            model_name=GEMINI_MODEL,
            system_instruction=_SYSTEM_INSTRUCTION,
        )
        logger.info(
            "GeminiClient initialized",
            extra={"model": GEMINI_MODEL, "region": GCP_REGION},
        )

    def generate_soap_note(
        self,
        transcript_text: str,
        session_duration_minutes: int = 50,
        file_id: str = "",
    ) -> SOAPNote:
        """
        Generate a structured SOAP note from a cleaned therapy transcript.

        Builds a multi-turn conversation including few-shot examples, then
        appends the actual transcript as the final user turn. Retries up to
        3 times on transient API errors.

        Args:
            transcript_text: Cleaned plain-text transcript (speaker-labeled).
            session_duration_minutes: Estimated session duration, used as a
                hint in the prompt if the model cannot infer it.
            file_id: Non-PHI Drive file ID, included in log entries for
                traceability.

        Returns:
            SOAPNote dataclass populated from Gemini's JSON response.

        Raises:
            GeminiError: If the API fails after retries or returns invalid JSON.
        """
        prompt_parts = self._build_prompt(transcript_text, session_duration_minutes)

        def _call_api():
            return self._model.generate_content(
                prompt_parts,
                generation_config=_GENERATION_CONFIG,
                safety_settings=_SAFETY_SETTINGS,
            )

        try:
            response = retry_with_backoff(
                _call_api,
                max_attempts=3,
                base_delay=2.0,
                max_delay=20.0,
                logger=logger,
            )
        except Exception as exc:
            raise GeminiError("Gemini API call failed after retries") from exc

        return self._parse_response(response, file_id=file_id)

    def _build_prompt(
        self, transcript_text: str, session_duration_minutes: int
    ) -> list[Part]:
        """
        Construct the full prompt as a list of content Parts.

        Structure:
          1. Few-shot example: user turn (transcript)
          2. Few-shot example: model turn (SOAP JSON)
          3. Actual user turn (transcript to process)
        """
        parts: list[Part] = []

        for example in _FEW_SHOT_EXAMPLES:
            parts.append(
                Part.from_text(
                    f"Transcript:\n{example['transcript'].strip()}"
                )
            )
            parts.append(Part.from_text(example["soap_note"]))

        # Final user turn: the actual transcript
        parts.append(
            Part.from_text(
                f"Transcript (estimated session duration: "
                f"{session_duration_minutes} minutes):\n\n"
                f"{transcript_text.strip()}"
            )
        )
        return parts

    def _parse_response(self, response: Any, file_id: str = "") -> SOAPNote:
        """
        Parse and validate Gemini's response into a SOAPNote.

        Args:
            response: GenerateContentResponse from the Vertex AI SDK.
            file_id: Non-PHI identifier for logging.

        Returns:
            Populated SOAPNote.

        Raises:
            GeminiError: If the response is empty, blocked, or not valid JSON,
                or if required SOAP keys are missing.
        """
        # Check for content filtering or empty response
        if not response.candidates:
            raise GeminiError(
                "Gemini returned no candidates — response may have been blocked"
            )

        candidate = response.candidates[0]
        if not candidate.content or not candidate.content.parts:
            finish_reason = getattr(candidate, "finish_reason", "UNKNOWN")
            raise GeminiError(
                f"Gemini candidate has no content parts. Finish reason: {finish_reason}"
            )

        raw_text = candidate.content.parts[0].text.strip()

        try:
            data = json.loads(raw_text)
        except json.JSONDecodeError as exc:
            raise GeminiError(
                f"Gemini response is not valid JSON: {exc}"
            ) from exc

        missing_keys = _REQUIRED_SOAP_KEYS - set(data.keys())
        if missing_keys:
            raise GeminiError(
                f"Gemini response missing required SOAP keys: {sorted(missing_keys)}"
            )

        # Coerce presenting_concerns to list if the model returned a string
        presenting_concerns = data.get("presenting_concerns", [])
        if isinstance(presenting_concerns, str):
            presenting_concerns = [
                line.lstrip("•-* ").strip()
                for line in presenting_concerns.splitlines()
                if line.strip()
            ]

        logger.info(
            "SOAP note generated successfully",
            extra={
                "file_id": file_id,
                "model": GEMINI_MODEL,
                "presenting_concern_count": len(presenting_concerns),
                "finish_reason": str(
                    getattr(candidate, "finish_reason", "UNKNOWN")
                ),
            },
        )

        return SOAPNote(
            subjective=str(data.get("subjective", "")),
            objective=str(data.get("objective", "")),
            assessment=str(data.get("assessment", "")),
            plan=str(data.get("plan", "")),
            session_duration_minutes=int(data.get("session_duration_minutes", 50)),
            presenting_concerns=presenting_concerns,
            risk_assessment=str(data.get("risk_assessment", "")),
            raw_json=data,
        )
